name: CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-describe pytest-spec pytest-mock

      - name: Run unit tests
        run: pytest --spec --color=yes test_battery.py

  functional-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Install Behave
        run: |
          pip install behave behave-webdriver

      - name: Run functional tests
        run: behave
